### ISSUE TITLE
1023 x 1023

### ISSUE THREAD

**Issue by marc365** [AmiDARK/Amos-Professional-AGA-Releases#3]
The original AMOS had a max screen dimension of 1023x1023 - this seems not supported by the AGA screen modes as it needs to be divisible. This may cause some impact to older AMOS programs that use this, also I have previously used Load Iff for any dimension image, so I believe that would be impacted also and limit images to be "standard" sizes? I will do some more tests with various dimensions but wanted to know if 1023 could be supported?

**Comment by AmiDARK** [comment]
From what I've understood in the "EcCree" method, when you see dimensions that are not multiple of 16 pixels, Amos Professional will automatically adjust the physical size to the higher multiple of 16 pixels value. In your case it will become a 1024x1024 screen.
With the update for AGA High resolution ( > 16 colors in hires resolution), I had to update this to be more restrictive.
In fact the Hires Aga mode required to used Fetch Mode x2 or higher (x4, etc.) due to this, I must align memory to 32 bits... I have updated the bitmap memory allocation to be 32 bits aligned, and forced size to be 32 bits multiple too. With that I have added more specific error message when entering invalid size. 
I think it's good for a language to be more structured without really changing command names.
More to this with the amount of changes I've done, it become really difficult to keep ECS compatibility (more slowdown, more complexity, risks of compatibility issues). Due to that I have entirely restructured AMos Pro AGA that now uses AmosProAGA.library instead of AMOS.library, and uses specific configuration files owning AGA in their names. It allow anyone to have bot Amos Pro 2.0 And Amos Pro AGA installed without conflicts.

**Comment by marc365** [comment]
ok, that sounds reasonable, I did see that I could run both versions. the developer would have to address this when they load the program in AmosProAga. not a problem really as to me 1023 seems like a bug in the code anyway as it won't allow 1024


`EcCree:	movem.l	d1-d7/a1-a6,-(sp)
	
;	Verifie les parametres
; ~~~~~~~~~~~~~~~~~~~~~~~~~~~~
	and.l	#$FFFFFFF0,d2
	beq	EcE4
	cmp.l	#1024,d2
	bcc	EcE4`
