### ISSUE TITLE
Syntax Error in Edit Objects and Edit Icons

### ISSUE THREAD

**Issue by bmpeter** [AmiDARK/Amos-Professional-AGA-Releases#6]
Hi,
if i start User->Edit Objects or User->Edit Icons i get the following error:

Error in previous Programm: Syntax Error

Can you please check?

**Comment by huggy70** [comment]
There is an error in line 393 of the source code of the object editor. Just replace the gibberish with command 'unpack' and save the program.
The error will go away but the program will crash upon upon opening :-(

**Comment by huggy70** [comment]
Just to clarify:
The Object editor will open without error if you'll make the changes. But in my case it crashes if there are objects loaded in the bank upon opening.

**Comment by AmiDARK** [comment]
Hello.

The issue with the Unpack method was already signaled here : https://github.com/AmiDARK/Amos-Professional-AGA-Releases/issues/4
It's due to the fact that I've inserted a new method using the ! naming convention to avoid entering several time the same command name (when command exists with various parameters amount.

The others crashs you can found with the "Object Editor" are linked to the fact that the "Object Editor" uses 2 banks containing compiler assembler. And these 2 compiled methods (zoom and another one I didn't check what it do) needs original Amos Professional to run correctly as they use its internal structure datas. The one in Amos Professional AGA was modified to handle 8 bitplanes and more colors making this 2 binaries banks incompatible with Amos Professional AGA.
The source code to create these 2 binaries banks was not provided in the original Amos Professional Source code.
Due to that, I cannot really fix them without hacking the binary.

As a result,these issues will not be fixed. I prefer thinking about developing (later, once Unity will be completed) a new Object Editor that will take benefits of AGA/SAGA capabilities as the current "Object Editor" is clearly outdated regarding the AGA improvements.

With all these, I close this issue.

Regards,.
